[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
basic_0 = "7RJ7c3E3rxFD3NScPVssfKk5psBVXEWjQBwPdex2DACE"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "pytest"
